name: 🚀 Deploy Website via SFTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: 📂 Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js to build React app
      - name: 📦 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Step 3: Install dependencies and build the React app
      - name: 📥 Install Dependencies
        run: |
          npm install
          npm run build

      # Step 4: Deploy files to DreamHost via SFTP
      - name: 🚀 Deploy to DreamHost
        uses: SamKirkland/FTP-Deploy-Action@4.5.0
        with:
          server: '${{ secrets.SFTP_HOST }}'       # Hostname from DreamHost
          username: '${{ secrets.SFTP_USERNAME }}' # DreamHost username
          password: '${{ secrets.SFTP_PASSWORD }}' # DreamHost password
          protocol: 'sftp'                         # Use SFTP for secure deployment
          local-dir: build/                        # Folder to deploy
          server-dir: /home/clcq/clcq.me/          # Directory on DreamHost
