name: 🚀 Deploy Website via SFTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout Repositor
        uses: actions/checkout@v3

      # Step 2: Set up Node.js to build React app
      - name: 📦 Set up Node.js
        uses: actions/setup-node@v4
        with:
        node-version: '18.x'  # You can specify a specific version or "lts"


      - name: 📥 Install Dependencies
        run: |
          npm install
          npm run build

      - name: 🔐 Add SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SFTP_SSH_KEY }}

      - name: 🚀 Deploy to DreamHost via SFTP
        uses: SamKirkland/FTP-Deploy-Action@4.5.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          protocol: 'sftp'
          local-dir: build/
          server-dir: /home/clcq/clcq.me/
