name: 🚀 Deploy Website via FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: 📂 Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js to build React app
      - name: 📦 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Step 3: Install dependencies and build the React app
      - name: 📥 Install Dependencies
        run: |
          npm install
          npm run build

      # Step 4: Upload files to FTP server using secrets
      - name: 🚀 Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.5.0
        with:
          server: ${{ secrets.FTP_HOST }}       # Reference the secret for FTP host
          username: ${{ secrets.FTP_USERNAME }} # Reference the secret for FTP username
          password: ${{ secrets.FTP_PASSWORD }} # Reference the secret for FTP password
          local-dir: build/
          server-dir: /clcq.me/                 # Change this to your correct Dreamhost server directory
