name: Test Secrets

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secrets
        run: |
          echo "SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}"
          echo "SFTP_HOST: ${{ secrets.SFTP_HOST }}"
        shell: bash