name: Test Secrets Op

on:
  push:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secrets
        run: |
          echo "SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}"
          echo "SFTP_HOST: ${{ secrets.SFTP_HOST }}"
        shell: bash