// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbsbrwhpkrxteolebfrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdic2Jyd2hwa3J4dGVvbGViZnJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjU2MTgyODMsImV4cCI6MjA0MTE5NDI4M30.qwbSBVVkqBDqlGt759YFdLbrHz_9UrHxmqXM5XfYU0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);