name: Deploy Website via SFTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install Dependencies and Build
        run: |
          CI=false yarn build # Set CI=false inline
          yarn add @babel/plugin-proposal-private-property-in-object -D
          yarn add @testing-library/react@latest -D
          yarn install
        shell: bash # Important: Specify bash shell

      - name: Run ESLint (Optional but highly recommended)
        run: yarn lint
        continue-on-error: true

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SFTP_SSH_KEY }}
          ssh-key-passphrase: ''

      - name: Deploy to DreamHost via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_HOST }}
          remote_dir: '/home/clcq/clcq.me/'
          local_dir: 'build/'
          over_ssh: true
