name: Test SSH Connection

on:
  push:
    branches:
      - main

jobs:
  test-ssh-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SFTP_SSH_KEY }}
          ssh-key-passphrase: ${{ secrets.SFTP_SSH_KEY_PASSPHRASE }}

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }} "echo 'SSH connection successful'"
