name: Build and Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SFTP_SSH_KEY }}
          ssh-key-passphrase: ${{ secrets.SFTP_SSH_KEY_PASSPHRASE }}

      - name: Verify SSH Key
        run: |
          ssh-add -l || echo "No SSH keys loaded"

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p 22 ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }} "echo 'SSH connection successful'"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install Dependencies and Build
        env:
          CI: false # Prevent CI from treating warnings as errors
        run: |
          yarn install
          yarn build || true # Continue even if the build fails

      - name: Deploy Build Files via SSH
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" ./build/ ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }}:/home/clcq/clcq.me/
